name: "blueBlog"
description: "This is a personal blog, please observe Think Hour for ad hoc quasi-diary writings and Big Ideas for my ratified longform items. I will see you there."

timezone: Europe/London
future: true

url: ''
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: _sass

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
