name: "Jekyll Untrue Minimal"
description: "This theme features an innovative no-title set up, beginning the page with a description of what the blog is about pursuant to function over form and divorced from branding philosophy."

url: ''
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/
